---
- name: Prepare host
  hosts: localhost
  roles:
    - common

- name: Install Jenkins
  hosts: localhost
  roles:
    - geerlingguy.jenkins

- hosts: localhost
  tasks:
    - name: Create Jenkins CI directory
      file:
        path: "{{ ci_dir }}/files"
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        mode: 0755
        state: directory

- name: Install jjb
  hosts: localhost
  roles:
    - jjb

- name: Install zuul
  hosts: localhost
  roles:
    - zuul

- name: Prepare Apache
  hosts: localhost
  roles:
    - apache
