credentials:
  os_username: %OS_USERNAME%
  os_password: %OS_PASSWORD%
  os_tenant: %OS_TENANT_NAME%
  os_auth_url: http://%OPENSTACK_HOST%:5000/v2.0
  sahara_url: http://localhost:8386/v1.1/%TENANT_ID%

network:
  type: %NETWORK%
  private_network: private
  public_network: public

clusters:
  - plugin_name: vanilla
    plugin_version: 2.6.0
    image: %vanilla_two_six_image%
    node_group_templates:
      - name: worker-dn-nm
        flavor_id: '20'
        node_processes:
          - datanode
          - nodemanager
        volumes_per_node: 2
        volumes_size: 2
        auto_security_group: true
        node_configs:
          &ng_configs
          MapReduce:
            yarn.app.mapreduce.am.resource.mb: 256
            yarn.app.mapreduce.am.command-opts: -Xmx256m
          YARN:
            yarn.scheduler.minimum-allocation-mb: 256
            yarn.scheduler.maximum-allocation-mb: 1024
            yarn.nodemanager.vmem-check-enabled: false
      - name: worker-nm
        flavor_id: '20'
        node_processes:
          - nodemanager
        auto_security_group: true
        node_configs:
          *ng_configs
      - name: worker-dn
        flavor_id: '20'
        node_processes:
          - datanode
        volumes_per_node: 2
        volumes_size: 2
        auto_security_group: true
        node_configs:
          *ng_configs
      - name: master-rm-nn-hvs
        flavor_id: '20'
        node_processes:
          - namenode
          - resourcemanager
          - hiveserver
        auto_security_group: true
        node_configs:
          *ng_configs
      - name: master-oo-hs-sn
        flavor_id: '20'
        node_processes:
          - oozie
          - historyserver
          - secondarynamenode
        auto_security_group: true
        node_configs:
          *ng_configs
    cluster:
        name: %cluster_name%
    cluster_template:
        name: vanilla-2-6-0
        node_group_templates:
            master-rm-nn-hvs: 1
            master-oo-hs-sn: 1
            worker-dn-nm: 2
            worker-dn: 1
            worker-nm: 1
        cluster_configs:
            HDFS:
                dfs.replication: 1
    scaling:
      - operation: resize
        node_group: worker-dn-nm
        size: 1
      - operation: resize
        node_group: worker-dn
        size: 0
      - operation: resize
        node_group: worker-nm
        size: 0
      - operation: add
        node_group: worker-dn
        size: 1
      - operation: add
        node_group: worker-nm
        size: 1
    edp_jobs_flow: vanilla_flow

edp_jobs_flow:
  vanilla_flow:
    - type: Pig
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      main_lib:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/example.pig
      additional_libs:
        - type: swift
          source: etc/edp-examples/edp-pig/trim-spaces/udf.jar
    - type: MapReduce
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      additional_libs:
        - type: database
          source:  etc/edp-examples/edp-mapreduce/edp-mapreduce.jar
      configs:
        mapred.mapper.class: org.apache.oozie.example.SampleMapper
        mapred.reducer.class: org.apache.oozie.example.SampleReducer
    - type: MapReduce.Streaming
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      configs:
        edp.streaming.mapper: /bin/cat
        edp.streaming.reducer: /usr/bin/wc
    - type: Java
      additional_libs:
        - type: database
          source: etc/edp-examples/hadoop2/edp-java/hadoop-mapreduce-examples-2.6.0.jar
      configs:
       edp.java.main_class: org.apache.hadoop.examples.QuasiMonteCarlo
      args:
        - 10
        - 10

