credentials:
  os_username: %OS_USERNAME%
  os_password: %OS_PASSWORD%
  os_tenant: %OS_TENANT_NAME%
  os_auth_url: http://%OPENSTACK_HOST%:5000/v2.0
  sahara_url: http://localhost:8386/v1.1/%TENANT_ID%

network:
  type: %NETWORK%
  private_network: private
  public_network: public

clusters:
  - plugin_name: spark
    plugin_version: 1.0.0
    image: %spark_image%
    node_group_templates:
      - name: master
        flavor_id: '20'
        node_processes:
          - master
          - namenode
        auto_security_group: true
      - name: worker
        flavor_id: '20'
        node_processes:
          - datanode
          - slave
        auto_security_group: true
    cluster_template:
      name: spark-1-0-0
      node_group_templates:
        master: 1
        worker: 1
      cluster_configs:
        HDFS:
          dfs.replication: 1
    cluster:
      name: %cluster_name%
    scenario:
      - run_jobs
    edp_jobs_flow: spark_edp

edp_jobs_flow:
  spark_edp:
    - type: Spark
      main_lib:
        type: database
        source: etc/edp-examples/edp-spark/spark-example.jar
      configs:
        edp.java.main_class: org.apache.spark.examples.SparkPi
      args:
        - 4
