---
- name: Create jjb directories
  file:
    path: "{{ item }}"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: 0755
    state: directory
  with_items:
    - /etc/jenkins_jobs
    - "{{ ci_dir }}/jjb"

- name: Clone jjb repo
  git:
    repo: "{{ jjb_git_url }}"
    dest: "{{ ci_dir}}/jjb"
  become: true
  become_user: "{{ jenkins_user }}"

- name: Install jjb  to virtualenv
  command: tox -e venv --notest
  args:
    chdir: "{{ ci_dir }}/jjb"
  become: true
  become_user: "{{ jenkins_user }}" 

- name: Copy configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/jenkins_jobs/{{ item }}"
  become: true
  with_items:
    - credentials.conf
    - jenkins_jobs.ini

- name: Create jjb symlink
  file:
    src: /opt/ci/jenkins-job-builder/.tox/venv/bin/jenkins-jobs
    dest: /usr/local/bin/jenkins-jobs
    state: link
