clusters:
  - plugin_name: fake
    plugin_version: "0.1"
    image: %fake_plugin_image%
    node_group_templates:
      - name: worker
        flavor_id: '20'
        node_processes:
          - datanode
          - tasktracker
        volumes_per_node: 2
        volumes_size: 2
        auto_security_group: true
      - name: master
        flavor_id: '20'
        node_processes:
          - jobtracker
          - namenode
        auto_security_group: true
    cluster_template:
      name: fake01
      node_group_templates:
        master: 1
        worker: 1
    cluster:
      name: %cluster_name%
    scaling:
      - operation: add
        node_group: worker
        size: 1
    edp_jobs_flow: transient
