clusters:
  - plugin_name: spark
    plugin_version: 1.0.0
    image: %spark_image%
    node_group_templates:
      - name: master
        flavor_id: '20'
        node_processes:
          - master
          - namenode
        auto_security_group: true
      - name: worker
        flavor_id: '20'
        node_processes:
          - datanode
          - slave
        auto_security_group: true
    cluster_template:
      name: spark-1-0-0
      node_group_templates:
        master: 1
        worker: 1
      cluster_configs:
        HDFS:
          dfs.replication: 1
    cluster:
      name: %cluster_name%
    scenario:
      - run_jobs
    edp_jobs_flow: spark_edp
