credentials:
  os_username: %OS_USERNAME%
  os_password: %OS_PASSWORD%
  os_tenant: %OS_TENANT_NAME%
  os_auth_url: http://%OPENSTACK_HOST%:5000/v2.0
  sahara_url: http://localhost:8386/v1.1/%TENANT_ID%

network:
  type: %NETWORK%
  private_network: private
  public_network: public

edp_jobs_flow:
  hadoop_2:
    - type: Pig
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/top-todoers/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      main_lib:
        type: swift
        source: etc/edp-examples/edp-pig/top-todoers/example.pig
    - type: MapReduce
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      additional_libs:
        - type: database
          source:  etc/edp-examples/edp-mapreduce/edp-mapreduce.jar
      configs:
        mapred.mapper.class: org.apache.oozie.example.SampleMapper
        mapred.reducer.class: org.apache.oozie.example.SampleReducer
    - type: MapReduce.Streaming
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      configs:
        edp.streaming.mapper: /bin/cat
        edp.streaming.reducer: /usr/bin/wc  
    - type: Java
      additional_libs:
        - type: database
          source: etc/edp-examples/hadoop2/edp-java/hadoop-mapreduce-examples-2.6.0.jar
      configs:
       edp.java.main_class: org.apache.hadoop.examples.QuasiMonteCarlo
      args:
        - 10
        - 10
  hadoop_1:
    - type: Pig
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/top-todoers/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      main_lib:
        type: swift
        source: etc/edp-examples/edp-pig/top-todoers/example.pig
    - type: MapReduce
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      additional_libs:
        - type: database
          source:  etc/edp-examples/edp-mapreduce/edp-mapreduce.jar
      configs:
        dfs.replication: 1
        mapred.mapper.class: org.apache.oozie.example.SampleMapper
        mapred.reducer.class: org.apache.oozie.example.SampleReducer
    - type: MapReduce.Streaming
      input_datasource:
        type: swift
        source: etc/edp-examples/edp-pig/trim-spaces/data/input
      output_datasource:
        type: hdfs
        destination: /user/hadoop/edp-output
      configs:
        edp.streaming.mapper: /bin/cat
        edp.streaming.reducer: /usr/bin/wc
    - type: Java
      additional_libs:
        - type: database
          source: etc/edp-examples/hadoop2/edp-java/edp-java.jar
      configs:
       edp.java.main_class: org.openstack.sahara.examples.WordCount
  spark_edp:
    - type: Spark
      main_lib:
        type: database
        source: etc/edp-examples/edp-spark/spark-example.jar
      configs:
        edp.java.main_class: org.apache.spark.examples.SparkPi
      args:
        - 4
