---
- name: Create zuul directories
  file:
    path: "{{ item }}"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_user }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ ci_dir }}/zuul"
    - /var/www/zuul
    - /etc/zuul
    - /var/log/zuul
    - /var/lib/zuul

- name: Create zuul files
  file:
    path: "{{ item }}"
    owner: "{{ zuul_user }}"
    group: "{{ zuul_user }}"
    mode: 0755
    state: touch
  with_items:
    - /etc/zuul/layout.yaml
    - /var/lib/zuul/times
    - /var/log/zuul/gearman-server

- name: Clone zuul repo
  git:
    repo: "{{ zuul_git_url }}"
    dest: "{{ ci_dir}}/zuul"
  become: true
  become_user: "{{ zuul_user }}"

- name: Install zuul to virtualenv
  command: tox -e venv --notest
  args:
    chdir: "{{ ci_dir }}/zuul"
  become: true
  become_user: "{{ zuul_user }}"

- name: Run fetch-dependencies
  command: "{{ ci_dir }}/zuul/etc/status/fetch-dependencies.sh"
  become: true

- name: Install zuul-ui
  command: "cp -r {{ ci_dir }}/zuul/etc/status/public_html /var/www/zuul/"
  become: true
  become_user: "{{ zuul_user }}"

- name: Copy zuul units
  copy:
    src: "{{ item }}"
    dest: "/lib/systemd/system/{{ item }}"
  become: true
  with_items:
    - zuul.service
    - zuul-merger.service

- name: Create zuul symlink
  file:
    src: "{{ ci_dir }}/zuul/.tox/venv/bin/zuul"
    dest: /usr/sbin/zuul-client
    state: link
