script-dir: /opt/ci/files/nodepool-scripts
images-dir: /opt/ci/files/nodepool_dib

cron:
  check: '*/1 * * * *'

zmq-publishers:
  - tcp://127.0.0.1:8888

gearman-servers:
  - host: 127.0.0.1

labels:
  - name:  stack-42
    image: stack-42
    min-ready: 1
    providers:
      - name: cilab-1
  - name:  stack-43
    image: stack-43
    min-ready: 1
    providers:
      - name: cilab-2

providers:
  - name: cilab-1
    username: 'ci-user'
    password: 'nova'
    auth-url: 'http://172.18.168.42:5000/v2.0'
    project-name: 'ci'
    max-servers: 3
    boot-timeout: 120
    ipv6-preferred: False
    pool: 'public'
    networks:
      - net-id: 'LAB_42_PRIVATE_NETWORK_ID'
    images:
      - name: stack-42
        base-image: 'ubuntu-16.04'
        min-ram: 4192
        private-key: '/etc/nodepool/id_dsa'
        setup: prepare_node.sh
  - name: cilab-2
    username: 'ci-user'
    password: 'nova'
    auth-url: 'http://172.18.168.43:5000/v2.0'
    project-name: 'ci'
    max-servers: 3
    boot-timeout: 120
    ipv6-preferred: False
    pool: 'public'
    networks:
      - net-id: 'LAB_43_PRIVATE_NETWORK_ID'
    images:
      - name: stack-43
        base-image: 'ubuntu-16.04'
        min-ram: 4192
        private-key: '/etc/nodepool/id_dsa'
        setup: prepare_node.sh

targets:
  - name: sahara-ci
